{
 "title": "Streams App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Kafka Streams Thread Commit Rate",
   "type": "graph",
   "description": "Number of Commits per Second across all Tasks in a thread\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_rate"
    }
   ]
  },
  {
   "title": "Table Readers Memory (MB)",
   "type": "graph",
   "description": "The estimated memory in MB used for reading Sorted Sequence Tables (SSTs), excluding memory used in block cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_estimate_table_readers_mem / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Num Entries Active MemTable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_num_entries_active_mem_table"
    }
   ]
  },
  {
   "title": "Streams Total SST File Size (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_total_sst_files_size / 1024 / 1024 "
    }
   ]
  },
  {
   "title": "Streams Thread Poll Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_ratio"
    }
   ]
  },
  {
   "title": "Block Cache Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_block_cache_usage"
    }
   ]
  },
  {
   "title": "Total Number of created tasks per thread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_task_created_total"
    }
   ]
  },
  {
   "title": "Streams State Store Estimated Number of Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_estimate_num_keys"
    }
   ]
  },
  {
   "title": "Streams Poll Latency Average (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg"
    }
   ]
  },
  {
   "title": "Stream Record Cache Metrics Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_avg"
    }
   ]
  },
  {
   "title": "Streams Threads Process Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_rate"
    }
   ]
  },
  {
   "title": "Block Cache Filter Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_block_cache_filter_hit_ratio"
    }
   ]
  },
  {
   "title": "Block Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_block_cache_data_hit_ratio"
    }
   ]
  }
 ]
}