spring:
  kafka:
    streams:
      application-id: ktable-test
      properties:
        acks: all
        security:
          protocol: PLAINTEXT
        bootstrap:
          servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.IntegerSerializer