spring:
  kafka:
    streams:
      application-id: ktable-test
      properties:
        acks: all
        security:
          protocol: PLAINTEXT
        bootstrap:
          servers: localhost:9092
