spring:
  kafka:
    streams:
      application-id: ktable-test
      properties:
        num:
          stream:
            threads: 12
        acks: all
        security:
          protocol: PLAINTEXT
        bootstrap:
          servers: localhost:9092
